# Generated by Django 6.0.1 on 2026-01-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='secondary_contact',
            field=models.CharField(blank=True, help_text='Enter secondary contact number with country code', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_addres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Enter ZIP or postal code', max_length=20, null=True),
        ),
    ]
