# Generated by Django 6.0.1 on 2026-01-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_customuser_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='street_addres',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
