# Generated by Django 6.0.1 on 2026-01-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='proof_files',
            field=models.FileField(blank=True, upload_to='claims/'),
        ),
    ]
